version: "3.8"

services:
  web:
    container_name: website
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - db
      - default

  db:
    container_name: postgres
    image: postgres:15.1-bullseye
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  db:

volumes:
  db: